### ISSUE TITLE
Docker Issues

### ISSUE THREAD

**Issue by ItsNoted** [Deleh/raincloud#1]
When running the docker command I get the following.
`
Error response from daemon: pull access denied for raincloud, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.`

**Comment by Deleh** [comment]
Thank you for the information.. Just added the Dockerfile yesterday and modified it over the day.
You should be able to build the image now with:

```
docker build -t raincloud:latest github.com/Deleh/raincloud
```

Was tested successfully on NixOS with podman and Ubuntu 20.04 with Docker.
